FROM mysql

RUN set -x \
    && apt-get update \
    && apt-get install -y bash unzip netcat

ENV VAULT_VERSION 0.7.0
ENV VAULT_SHA256 c6d97220e75335f75bd6f603bb23f1f16fe8e2a9d850ba59599b1a0e4d067aaa

ADD https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip /tmp/vault.zip

RUN echo "${VAULT_SHA256}  /tmp/vault.zip" > /tmp/vault.sha256 \
&& sha256sum -c /tmp/vault.sha256 \
&& cd /bin \
&& unzip /tmp/vault.zip \
&& chmod +x /bin/vault \
&& rm /tmp/vault.zip

ENV ENVCONSUL_VERSION 0.6.2
ENV ENVCONSUL_SHA256 c86ecd5b1cac5b6d59326e495809ce4778ecca0bf2e41b2a650613b865f2565b

ADD https://releases.hashicorp.com/envconsul/${ENVCONSUL_VERSION}/envconsul_${ENVCONSUL_VERSION}_linux_amd64.zip /tmp/envconsul.zip
RUN echo "${ENVCONSUL_SHA256}  /tmp/envconsul.zip" > /tmp/envconsul.sha256 \
  && sha256sum -c /tmp/envconsul.sha256 \
  && cd /bin \
  && unzip /tmp/envconsul.zip \
  && chmod +x /bin/envconsul \
  && rm /tmp/envconsul.zip

WORKDIR /
COPY mysql_test.sh /
RUN chmod +x mysql_test.sh

ENTRYPOINT ["/mysql_test.sh"]
